name: Build and run

on: push

permissions: {}

env:
  SIMPLE_APP: |
    #include <stdlib.h>
    #include <stdio.h>
    #include <sys/types.h>
    #include <dirent.h>

    int main(int argc, char *argv[]) {
      DIR *d;
      struct dirent *de;
      puts("Hello!");
      puts(argv[0]);
      if(argv[1]) {
        puts(argv[1]);
        d = opendir(argv[1]);
        if(d != NULL) {
          while((de = readdir(d)) != NULL) {
            puts(de->d_name);
          }
          closedir(d);
        }
      }

      return 0;
    }

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install kraft
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p $HOME/.local/bin
          cd $HOME/.local/bin
          tag=$(gh -R unikraft/kraftkit release list -L 1 --exclude-pre-releases --exclude-drafts --json tagName | jq -r '.[0]|.tagName')
          wget --no-verbose https://github.com/unikraft/kraftkit/releases/download/${tag}/kraft_${tag#v}_linux_arm64.tar.gz
          tar xvaf *.tar.gz
          rm *.tar.gz
          echo "$PWD" >> "$GITHUB_PATH"
      - name: Build
        run: |
          kraft build --target qemu/arm64
      - name: Display the configuration
        run: |
          set -x
          cat .config.*
        if: ${{ always() }}
      - name: Create a simple initrd
        run: |
          printf %s "$SIMPLE_APP" > prog.c
          set -x
          gcc -fPIC -Wall -static-pie prog.c -o prog
          echo prog | cpio -o -H newc > initrd.cpio
      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-arm
      - name: Run the unikernel
        run: |
          set -x
          cp .unikraft/build/elfloader_qemu-arm64 kernel
          ls -al /dev/kvm* || true
          qemu-system-aarch64 -nographic -nodefaults -serial stdio \
            -machine virt -cpu max \
            -m 64 \
            -kernel kernel \
            -append 'dummyfirstarg vfs.fstab=[ "initrd0:/:extract::ramfs=1:" "fs9p:/data:9pfs:::mkmp" ] -- /prog /data' \
            -initrd initrd.cpio \
            -virtfs local,path="$PWD",mount_tag=fs9p,security_model=none
